name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Build Docker image
      run: docker build -t payment-gateway .
    - name: Push Docker image to registry
      run: docker push your-docker-repo/payment-gateway:latest
    - name: Deploy to AWS
      uses: some-aws-deployment-action
